process_image:
  name: Process Image
  description: Manually trigger image processing for a specific sensor entity
  fields:
    entity_id:
      name: Entity ID
      description: The entity ID of the Image to Sensor CV sensor to process
      required: true
      selector:
        entity:
          domain: sensor
          integration: image_to_sensor_cv